#ifndef STM32F429I_DISCO
#define STM32F429I_DISCO


#define LED1_PORT			IOJ
#define LED1_PIN			13
#define LED1_INVERSE		false

#define LED2_PORT			IOJ
#define LED2_PIN			5
#define LED2_INVERSE		false

/*#define LED3_PORT			IOD
#define LED3_PIN			5
#define LED3_INVERSE		true

#define LED4_PORT			IOK
#define LED4_PIN			3
#define LED4_INVERSE		true*/

#define LEDS_NR				2

#define HARDBTN1_PORT		IOA
#define HARDBTN1_PIN		0

#define HARDBTNS_NR			1

#define DEFAULT_UART_UNIT		0
#define DEFAULT_UART_TX_PORT	IOA
#define DEFAULT_UART_TX_PIN		9
#define DEFAULT_UART_RX_PORT	IOA
#define DEFAULT_UART_RX_PIN		10

#define DEFAULT_I2C_UNIT		0
#define DEFAULT_I2C_SCL_PORT	IOB
#define DEFAULT_I2C_SCL_PIN		8
#define DEFAULT_I2C_SDA_PORT	IOB
#define DEFAULT_I2C_SDA_PIN		9

#define AUDIO_LCD_I2C_UNIT		3
#define AUDIO_LCD_I2C_SCL_PORT	IOD
#define AUDIO_LCD_I2C_SCL_PIN	12
#define AUDIO_LCD_I2C_SDA_PORT	IOB
#define AUDIO_LCD_I2C_SDA_PIN	7

#define SPI_EXTENSION_UNIT		1
#define SPI_EXTENSION_SCK_PORT	IOA
#define SPI_EXTENSION_SCK_PIN	12
#define SPI_EXTENSION_MOSI_PORT	IOB
#define SPI_EXTENSION_MOSI_PIN	15
#define SPI_EXTENSION_MISO_PORT	IOB
#define SPI_EXTENSION_MISO_PIN	14
#define SPI_EXTENSION_CS1_PORT	IOA//SD_CD
#define SPI_EXTENSION_CS1_PIN	11

#define LCD_BACKLIGHT_PORT		IOI
#define LCD_BACKLIGHT_PIN		14
#define LCD_DISPLAY_RST_PORT	IOJ
#define LCD_DISPLAY_RST_PIN		15
#define LCD_TOUCH_INT_PORT		IOI
#define LCD_TOUCH_INT_PIN		13

#define SD_CD_PORT				IOI
#define SD_CD_PIN				15

//#define BAT_STAT_PORT			IOC
//#define BAT_STAT_PIN			13

#endif
