#ifndef SMARTRF_SETTINGS_H
#define SMARTRF_SETTINGS_H


//*********************************************************************************
// These settings has been generated for use with TI-RTOS and cc13xxware
//
// Generated by SmartRF Studio version 2.2.1
// Tested with TI-RTOS version tirtos_simplelink_2_14_02
//
//*********************************************************************************
#include "driver/rf_mailbox.h"
#include "driver/rf_common_cmd.h"
#include "driver/rf_prop_cmd.h"
#include "driver/rfc.h"


// TI-RTOS RF Mode Object
//extern RF_Mode RF_prop;


// RF Core API commands
extern const rfc_CMD_PROP_RADIO_DIV_SETUP_t RF_cmdPropRadioDivSetup;
extern const rfc_CMD_FS_t RF_cmdFs;
extern const rfc_CMD_PROP_TX_t RF_cmdPropTx;
extern const rfc_CMD_PROP_RX_t RF_cmdPropRx;




#endif // SMARTRF_SETTINGS_H
