/*
 * lcd.c
 *
 *  Created on: Feb 2, 2013
 *      Author: XxXx
 */


#include "lcd.h"
#include "include/hw.h"

void lcd_set_dma_buff_addr(unsigned int instance_nr, unsigned int buff_base_addr)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_BA(0)) = buff_base_addr;
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_BA(1)) = buff_base_addr;
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_BA(0)) = buff_base_addr;
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_BA(1)) = buff_base_addr;
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_BA(0)) = buff_base_addr;
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_BA(1)) = buff_base_addr;
		break;
	}
}

void lcd_set_buff_preload_mode(unsigned int instance_nr, unsigned int type)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_BUFPRELOAD_bm) | ((type << DISPC_VID_ATTRIBUTES_BUFPRELOAD_bp) & DISPC_VID_ATTRIBUTES_BUFPRELOAD_bm);
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_BUFPRELOAD_bm) | ((type << DISPC_VID_ATTRIBUTES_BUFPRELOAD_bp) & DISPC_VID_ATTRIBUTES_BUFPRELOAD_bm);
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID3_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_BUFPRELOAD_bm) | ((type << DISPC_VID_ATTRIBUTES_BUFPRELOAD_bp) & DISPC_VID_ATTRIBUTES_BUFPRELOAD_bm);
		break;
	}
}

void lcd_set_burst_type(unsigned int instance_nr, unsigned int burst_type)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_BURSTTYPE_bm) | ((burst_type << DISPC_VID_ATTRIBUTES_BURSTTYPE_bp) & DISPC_VID_ATTRIBUTES_BURSTTYPE_bm);
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_BURSTTYPE_bm) | ((burst_type << DISPC_VID_ATTRIBUTES_BURSTTYPE_bp) & DISPC_VID_ATTRIBUTES_BURSTTYPE_bm);
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID3_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_BURSTTYPE_bm) | ((burst_type << DISPC_VID_ATTRIBUTES_BURSTTYPE_bp) & DISPC_VID_ATTRIBUTES_BURSTTYPE_bm);
		break;
	}
}

void lcd_set_burst_size(unsigned int instance_nr, unsigned int burst_size)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_BURSTSIZE_gm) | ((burst_size << DISPC_VID_ATTRIBUTES_BURSTSIZE_gp) & DISPC_VID_ATTRIBUTES_BURSTSIZE_gm);
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_BURSTSIZE_gm) | ((burst_size << DISPC_VID_ATTRIBUTES_BURSTSIZE_gp) & DISPC_VID_ATTRIBUTES_BURSTSIZE_gm);
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID3_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_BURSTSIZE_gm) | ((burst_size << DISPC_VID_ATTRIBUTES_BURSTSIZE_gp) & DISPC_VID_ATTRIBUTES_BURSTSIZE_gm);
		break;
	}
}

void lcd_set_rotation(unsigned int instance_nr, unsigned int rotation)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_ROTATION_gm) | ((rotation << DISPC_VID_ATTRIBUTES_ROTATION_gp) & DISPC_VID_ATTRIBUTES_ROTATION_gm);
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_ROTATION_gm) | ((rotation << DISPC_VID_ATTRIBUTES_ROTATION_gp) & DISPC_VID_ATTRIBUTES_ROTATION_gm);
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_ROTATION_gm) | ((rotation << DISPC_VID_ATTRIBUTES_ROTATION_gp) & DISPC_VID_ATTRIBUTES_ROTATION_gm);
		break;
	}
}

void lcd_set_self_refresh(unsigned int instance_nr, unsigned int value)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_SELFREFRESH_bm) | ((value << DISPC_VID_ATTRIBUTES_SELFREFRESH_bp) & DISPC_VID_ATTRIBUTES_SELFREFRESH_bm);
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_SELFREFRESH_bm) | ((value << DISPC_VID_ATTRIBUTES_SELFREFRESH_bp) & DISPC_VID_ATTRIBUTES_SELFREFRESH_bm);
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_SELFREFRESH_bm) | ((value << DISPC_VID_ATTRIBUTES_SELFREFRESH_bp) & DISPC_VID_ATTRIBUTES_SELFREFRESH_bm);
		break;
	}
}

void lcd_set_pipeline_priority(unsigned int instance_nr, unsigned int value)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_ARBITRATION_bm) | ((value << DISPC_VID_ATTRIBUTES_ARBITRATION_bp) & DISPC_VID_ATTRIBUTES_ARBITRATION_bm);
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID2_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_ARBITRATION_bm) | ((value << DISPC_VID_ATTRIBUTES_ARBITRATION_bp) & DISPC_VID_ATTRIBUTES_ARBITRATION_bm);
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_ATTRIBUTES) = (HWREG(DISPC_BASE_ADDR + DISPC_VID3_ATTRIBUTES) & ~DISPC_VID_ATTRIBUTES_ARBITRATION_bm) | ((value << DISPC_VID_ATTRIBUTES_ARBITRATION_bp) & DISPC_VID_ATTRIBUTES_ARBITRATION_bm);
		break;
	}
}

void lcd_set_row_increment(unsigned int instance_nr, unsigned int increment)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_ROW_INC) = increment;
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_ROW_INC) = increment;
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_ROW_INC) = increment;
		break;
	}
}

void lcd_set_pixel_increment(unsigned int instance_nr, unsigned int increment)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_PIXEL_INC) = increment & 0xFF;
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_PIXEL_INC) = increment & 0xFF;
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_PIXEL_INC) = increment & 0xFF;
		break;
	}
}

void lcd_set_x_original_image(unsigned int instance_nr, unsigned int size)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_PICTURE_SIZE) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_PICTURE_SIZE) & ~DISPC_VID_PICTURE_SIZE_X_gm) | ((size << DISPC_VID_PICTURE_SIZE_X_gp) & DISPC_VID_PICTURE_SIZE_X_gm);
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_PICTURE_SIZE) = (HWREG(DISPC_BASE_ADDR + DISPC_VID2_PICTURE_SIZE) & ~DISPC_VID_PICTURE_SIZE_X_gm) | ((size << DISPC_VID_PICTURE_SIZE_X_gp) & DISPC_VID_PICTURE_SIZE_X_gm);
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_PICTURE_SIZE) = (HWREG(DISPC_BASE_ADDR + DISPC_VID3_PICTURE_SIZE) & ~DISPC_VID_PICTURE_SIZE_X_gm) | ((size << DISPC_VID_PICTURE_SIZE_X_gp) & DISPC_VID_PICTURE_SIZE_X_gm);
		break;
	}
}

void lcd_set_y_original_image(unsigned int instance_nr, unsigned int size)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_PICTURE_SIZE) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_PICTURE_SIZE) & ~DISPC_VID_PICTURE_SIZE_Y_gm) | ((size << DISPC_VID_PICTURE_SIZE_Y_gp) & DISPC_VID_PICTURE_SIZE_Y_gm);
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_PICTURE_SIZE) = (HWREG(DISPC_BASE_ADDR + DISPC_VID2_PICTURE_SIZE) & ~DISPC_VID_PICTURE_SIZE_Y_gm) | ((size << DISPC_VID_PICTURE_SIZE_Y_gp) & DISPC_VID_PICTURE_SIZE_Y_gm);
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_PICTURE_SIZE) = (HWREG(DISPC_BASE_ADDR + DISPC_VID3_PICTURE_SIZE) & ~DISPC_VID_PICTURE_SIZE_Y_gm) | ((size << DISPC_VID_PICTURE_SIZE_Y_gp) & DISPC_VID_PICTURE_SIZE_Y_gm);
		break;
	}
}

void lcd_set_set_preload_value(unsigned int instance_nr, unsigned int value)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_PRELOAD) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_PRELOAD) & ~DISPC_VID_PRELOAD_gm) | ((value << DISPC_VID_PRELOAD_gp) & DISPC_VID_PRELOAD_gm);
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_PRELOAD) = (HWREG(DISPC_BASE_ADDR + DISPC_VID2_PRELOAD) & ~DISPC_VID_PRELOAD_gm) | ((value << DISPC_VID_PRELOAD_gp) & DISPC_VID_PRELOAD_gm);
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_PRELOAD) = (HWREG(DISPC_BASE_ADDR + DISPC_VID3_PRELOAD) & ~DISPC_VID_PRELOAD_gm) | ((value << DISPC_VID_PRELOAD_gp) & DISPC_VID_PRELOAD_gm);
		break;
	}
}

void lcd_set_dma_fifo_high_treshold(unsigned int instance_nr, unsigned int fifo_treshold)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_BUF_THRESHOLD) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_BUF_THRESHOLD) & ~DISPC_VID_BUF_THRESHOLD_BUFHIGHTHRESHOLD_gm) | ((fifo_treshold << DISPC_VID_BUF_THRESHOLD_BUFHIGHTHRESHOLD_gp) & DISPC_VID_BUF_THRESHOLD_BUFHIGHTHRESHOLD_gm);
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_BUF_THRESHOLD) = (HWREG(DISPC_BASE_ADDR + DISPC_VID2_BUF_THRESHOLD) & ~DISPC_VID_BUF_THRESHOLD_BUFHIGHTHRESHOLD_gm) | ((fifo_treshold << DISPC_VID_BUF_THRESHOLD_BUFHIGHTHRESHOLD_gp) & DISPC_VID_BUF_THRESHOLD_BUFHIGHTHRESHOLD_gm);
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_BUF_THRESHOLD) = (HWREG(DISPC_BASE_ADDR + DISPC_VID3_BUF_THRESHOLD) & ~DISPC_VID_BUF_THRESHOLD_BUFHIGHTHRESHOLD_gm) | ((fifo_treshold << DISPC_VID_BUF_THRESHOLD_BUFHIGHTHRESHOLD_gp) & DISPC_VID_BUF_THRESHOLD_BUFHIGHTHRESHOLD_gm);
		break;
	}
}

void lcd_set_dma_fifo_low_treshold(unsigned int instance_nr, unsigned int fifo_treshold)
{
	switch(instance_nr)
	{
	case 1:
		HWREG(DISPC_BASE_ADDR + DISPC_VID1_BUF_THRESHOLD) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_BUF_THRESHOLD) & ~DISPC_VID_BUF_THRESHOLD_BUFLOWTHRESHOLD_gm) | ((fifo_treshold << DISPC_VID_BUF_THRESHOLD_BUFLOWTHRESHOLD_gp) & DISPC_VID_BUF_THRESHOLD_BUFLOWTHRESHOLD_gm);
		break;
	case 2:
		HWREG(DISPC_BASE_ADDR + DISPC_VID2_BUF_THRESHOLD) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_BUF_THRESHOLD) & ~DISPC_VID_BUF_THRESHOLD_BUFLOWTHRESHOLD_gm) | ((fifo_treshold << DISPC_VID_BUF_THRESHOLD_BUFLOWTHRESHOLD_gp) & DISPC_VID_BUF_THRESHOLD_BUFLOWTHRESHOLD_gm);
		break;
	case 3:
		HWREG(DISPC_BASE_ADDR + DISPC_VID3_BUF_THRESHOLD) = (HWREG(DISPC_BASE_ADDR + DISPC_VID1_BUF_THRESHOLD) & ~DISPC_VID_BUF_THRESHOLD_BUFLOWTHRESHOLD_gm) | ((fifo_treshold << DISPC_VID_BUF_THRESHOLD_BUFLOWTHRESHOLD_gp) & DISPC_VID_BUF_THRESHOLD_BUFLOWTHRESHOLD_gm);
		break;
	}
}
/*******************************************************************************/





