/*
 * pin_mux_mii.c
 *
 *  Created on: Aug 15, 2012
 *      Author: Iulian Gheorghiu morgoth2600@gmail.com
 */

#include "board_properties.h"
#include "pin_mux_cpsw.h"

/**
 * \brief   This function sets the RGMII mode for both ports
 *
 * \param   None
 *
 * \return  None.
 */
void EVMPortMIIModeSelect(void)
{
    /* Select MII, Internal Delay mode */
    HWREG(SOC_CONTROL_REGS + CONTROL_GMII_SEL) = 0x00;
}

unsigned int CPSWPinMuxSetup(unsigned int MiiNr)
{
	switch(MiiNr)
	{
	case 1:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXERR) =
		        CONTROL_CONF_MII1_RXERR_CONF_MII1_RXERR_RXACTIVE | CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXEN) =  CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXDV) =
		         CONTROL_CONF_MII1_RXDV_CONF_MII1_RXDV_RXACTIVE | CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXD3) =  CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXD2) =  CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXD1) =  CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXD0) =  CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXCLK) =
		          CONTROL_CONF_MII1_TXCLK_CONF_MII1_TXCLK_RXACTIVE | CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXCLK) =
		         CONTROL_CONF_MII1_RXCLK_CONF_MII1_RXCLK_RXACTIVE | CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXD3) =
		         CONTROL_CONF_MII1_RXD3_CONF_MII1_RXD3_RXACTIVE | CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXD2) =
		         CONTROL_CONF_MII1_RXD2_CONF_MII1_RXD2_RXACTIVE | CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXD1) =
		         CONTROL_CONF_MII1_RXD1_CONF_MII1_RXD1_RXACTIVE | CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXD0) =
		         CONTROL_CONF_MII1_RXD0_CONF_MII1_RXD0_RXACTIVE | CPSW_MII_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MDIO_DATA) =
		         CONTROL_CONF_MDIO_DATA_CONF_MDIO_DATA_RXACTIVE
		         | CONTROL_CONF_MDIO_DATA_CONF_MDIO_DATA_PUTYPESEL
		         | CPSW_MDIO_SEL_MODE;
		    HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MDIO_CLK) =
		         CONTROL_CONF_MDIO_CLK_CONF_MDIO_CLK_PUTYPESEL | CPSW_MDIO_SEL_MODE;
		break;
	default:
		return 0;
	}
	return 1;
}

