/*
 * pin_mux_mmcsd.c
 *
 *  Created on: Aug 15, 2012
 *      Author: Iulian Gheorghiu morgoth2600@gmail.com
 */

#include "pin_mux_mmcsd.h"
/**********************************************/
void pin_mux_mmcsd_beaglebone(unsigned int MmcsdNr)
{
	switch(MmcsdNr)
	{
		case 0:
			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_DAT3) =
						   (0 << CONTROL_CONF_MMC0_DAT3_CONF_MMC0_DAT3_MMODE_SHIFT)    |
						   (0 << CONTROL_CONF_MMC0_DAT3_CONF_MMC0_DAT3_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_MMC0_DAT3_CONF_MMC0_DAT3_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_MMC0_DAT3_CONF_MMC0_DAT3_RXACTIVE_SHIFT);

			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_DAT2) =
						   (0 << CONTROL_CONF_MMC0_DAT2_CONF_MMC0_DAT2_MMODE_SHIFT)    |
						   (0 << CONTROL_CONF_MMC0_DAT2_CONF_MMC0_DAT2_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_MMC0_DAT2_CONF_MMC0_DAT2_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_MMC0_DAT2_CONF_MMC0_DAT2_RXACTIVE_SHIFT);

			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_DAT1) =
						   (0 << CONTROL_CONF_MMC0_DAT1_CONF_MMC0_DAT1_MMODE_SHIFT)    |
						   (0 << CONTROL_CONF_MMC0_DAT1_CONF_MMC0_DAT1_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_MMC0_DAT1_CONF_MMC0_DAT1_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_MMC0_DAT1_CONF_MMC0_DAT1_RXACTIVE_SHIFT);

			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_DAT0) =
						   (0 << CONTROL_CONF_MMC0_DAT0_CONF_MMC0_DAT0_MMODE_SHIFT)    |
						   (0 << CONTROL_CONF_MMC0_DAT0_CONF_MMC0_DAT0_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_MMC0_DAT0_CONF_MMC0_DAT0_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_MMC0_DAT0_CONF_MMC0_DAT0_RXACTIVE_SHIFT);

			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_CLK) =
						   (0 << CONTROL_CONF_MMC0_CLK_CONF_MMC0_CLK_MMODE_SHIFT)    |
						   (0 << CONTROL_CONF_MMC0_CLK_CONF_MMC0_CLK_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_MMC0_CLK_CONF_MMC0_CLK_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_MMC0_CLK_CONF_MMC0_CLK_RXACTIVE_SHIFT);

			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_CMD) =
						   (0 << CONTROL_CONF_MMC0_CMD_CONF_MMC0_CMD_MMODE_SHIFT)    |
						   (0 << CONTROL_CONF_MMC0_CMD_CONF_MMC0_CMD_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_MMC0_CMD_CONF_MMC0_CMD_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_MMC0_CMD_CONF_MMC0_CMD_RXACTIVE_SHIFT);
			break;
		case 1:
			/* clk*/
			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_CSN(1)) =
						   (2 << CONTROL_CONF_GPMC_CSN1_CONF_GPMC_CSN1_MMODE_SHIFT)    |
						   (0 << CONTROL_CONF_GPMC_CSN1_CONF_GPMC_CSN1_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_CSN1_CONF_GPMC_CSN1_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_GPMC_CSN1_CONF_GPMC_CSN1_RXACTIVE_SHIFT);
			/* cmd*/
			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_CSN(2)) =
						   (2 << CONTROL_CONF_GPMC_CSN2_CONF_GPMC_CSN2_MMODE_SHIFT)    |
						   (0 << CONTROL_CONF_GPMC_CSN2_CONF_GPMC_CSN2_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_CSN2_CONF_GPMC_CSN2_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_GPMC_CSN2_CONF_GPMC_CSN2_RXACTIVE_SHIFT);
			/* dat0*/
			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(0)) =
						   (1 << CONTROL_CONF_GPMC_AD0_CONF_GPMC_AD0_MMODE_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD0_CONF_GPMC_AD0_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD0_CONF_GPMC_AD0_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_GPMC_AD0_CONF_GPMC_AD0_RXACTIVE_SHIFT);
			/* dat1*/
			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(1)) =
						   (1 << CONTROL_CONF_GPMC_AD1_CONF_GPMC_AD1_MMODE_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD1_CONF_GPMC_AD1_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD1_CONF_GPMC_AD1_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_GPMC_AD1_CONF_GPMC_AD1_RXACTIVE_SHIFT);
			/* dat2*/
			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(2)) =
						   (1 << CONTROL_CONF_GPMC_AD2_CONF_GPMC_AD2_MMODE_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD2_CONF_GPMC_AD2_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD2_CONF_GPMC_AD2_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_GPMC_AD2_CONF_GPMC_AD2_RXACTIVE_SHIFT);
			/* dat3*/
			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(3)) =
						   (1 << CONTROL_CONF_GPMC_AD3_CONF_GPMC_AD3_MMODE_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD3_CONF_GPMC_AD3_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD3_CONF_GPMC_AD3_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_GPMC_AD3_CONF_GPMC_AD3_RXACTIVE_SHIFT);
			/* dat4*/
			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(4)) =
						   (1 << CONTROL_CONF_GPMC_AD4_CONF_GPMC_AD4_MMODE_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD4_CONF_GPMC_AD4_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD4_CONF_GPMC_AD4_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_GPMC_AD4_CONF_GPMC_AD4_RXACTIVE_SHIFT);
			/* dat5*/
			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(5)) =
						   (1 << CONTROL_CONF_GPMC_AD5_CONF_GPMC_AD5_MMODE_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD5_CONF_GPMC_AD5_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD5_CONF_GPMC_AD5_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_GPMC_AD5_CONF_GPMC_AD5_RXACTIVE_SHIFT);
			/* dat6*/
			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(6)) =
						   (1 << CONTROL_CONF_GPMC_AD6_CONF_GPMC_AD6_MMODE_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD6_CONF_GPMC_AD6_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD6_CONF_GPMC_AD6_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_GPMC_AD6_CONF_GPMC_AD6_RXACTIVE_SHIFT);
			/* dat7*/
			HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(7)) =
						   (1 << CONTROL_CONF_GPMC_AD7_CONF_GPMC_AD7_MMODE_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD7_CONF_GPMC_AD7_PUDEN_SHIFT)    |
						   (1 << CONTROL_CONF_GPMC_AD7_CONF_GPMC_AD7_PUTYPESEL_SHIFT)|
						   (1 << CONTROL_CONF_GPMC_AD7_CONF_GPMC_AD7_RXACTIVE_SHIFT);
	}
}
/**********************************************/
unsigned int pin_mux_mmcsd0_clk(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd0_Clk_PinMux_G17:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_CLK) =
					   (0 << CONTROL_CONF_MMC0_CLK_CONF_MMC0_CLK_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MMC0_CLK_CONF_MMC0_CLK_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MMC0_CLK_CONF_MMC0_CLK_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MMC0_CLK_CONF_MMC0_CLK_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(0));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd0_cmd(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd0_Cmd_PinMux_G18:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_CMD) =
					   (0 << CONTROL_CONF_MMC0_CMD_CONF_MMC0_CMD_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MMC0_CMD_CONF_MMC0_CMD_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MMC0_CMD_CONF_MMC0_CMD_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MMC0_CMD_CONF_MMC0_CMD_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(0));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd0_dat0(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd0_Dat0_PinMux_G16:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_DAT0) =
					   (0 << CONTROL_CONF_MMC0_DAT0_CONF_MMC0_DAT0_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MMC0_DAT0_CONF_MMC0_DAT0_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MMC0_DAT0_CONF_MMC0_DAT0_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MMC0_DAT0_CONF_MMC0_DAT0_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(0));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd0_dat1(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd0_Dat1_PinMux_G15:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_DAT1) =
					   (0 << CONTROL_CONF_MMC0_DAT1_CONF_MMC0_DAT1_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MMC0_DAT1_CONF_MMC0_DAT1_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MMC0_DAT1_CONF_MMC0_DAT1_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MMC0_DAT1_CONF_MMC0_DAT1_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(0));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd0_dat2(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd0_Dat2_PinMux_F18:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_DAT2) =
					   (0 << CONTROL_CONF_MMC0_DAT2_CONF_MMC0_DAT2_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MMC0_DAT2_CONF_MMC0_DAT2_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MMC0_DAT2_CONF_MMC0_DAT2_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MMC0_DAT2_CONF_MMC0_DAT2_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(0));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd0_dat3(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd0_Dat3_PinMux_F17:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MMC0_DAT3) =
					   (0 << CONTROL_CONF_MMC0_DAT3_CONF_MMC0_DAT3_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MMC0_DAT3_CONF_MMC0_DAT3_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MMC0_DAT3_CONF_MMC0_DAT3_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MMC0_DAT3_CONF_MMC0_DAT3_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(0));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd0_dat4(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd0_Dat4_PinMux_L16:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXD2) =
					   (0 << CONTROL_CONF_MII1_RXD2_CONF_MII1_RXD2_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_RXD2_CONF_MII1_RXD2_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_RXD2_CONF_MII1_RXD2_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_RXD2_CONF_MII1_RXD2_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd0_dat5(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd0_Dat5_PinMux_L17:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXD3) =
					   (0 << CONTROL_CONF_MII1_RXD3_CONF_MII1_RXD3_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_RXD3_CONF_MII1_RXD3_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_RXD3_CONF_MII1_RXD3_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_RXD3_CONF_MII1_RXD3_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd0_dat6(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd0_Dat6_PinMux_L18:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXCLK) =
					   (0 << CONTROL_CONF_MII1_RXCLK_CONF_MII1_RXCLK_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_RXCLK_CONF_MII1_RXCLK_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_RXCLK_CONF_MII1_RXCLK_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_RXCLK_CONF_MII1_RXCLK_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd0_dat7(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd0_Dat7_PinMux_K18:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXCLK) =
					   (0 << CONTROL_CONF_MII1_TXCLK_CONF_MII1_TXCLK_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_TXCLK_CONF_MII1_TXCLK_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_TXCLK_CONF_MII1_TXCLK_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_TXCLK_CONF_MII1_TXCLK_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	default:
		return 0;
	}
	return 1;
}
/**********************************************/
unsigned int pin_mux_mmcsd1_clk(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd1_Clk_PinMux_U9:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_CSN(1)) =
					   (0 << CONTROL_CONF_GPMC_CSN1_CONF_GPMC_CSN1_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_CSN1_CONF_GPMC_CSN1_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_CSN1_CONF_GPMC_CSN1_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_CSN1_CONF_GPMC_CSN1_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(2));
		break;
	case Mmcsd1_Clk_PinMux_K17:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXD0) =
					   (0 << CONTROL_CONF_MII1_TXD0_CONF_MII1_TXD0_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_TXD0_CONF_MII1_TXD0_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_TXD0_CONF_MII1_TXD0_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_TXD0_CONF_MII1_TXD0_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(6));
		break;
	case Mmcsd1_Clk_PinMux_M18:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MDIO_CLK) =
					   (0 << CONTROL_CONF_MDIO_CLK_CONF_MDIO_CLK_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MDIO_CLK_CONF_MDIO_CLK_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MDIO_CLK_CONF_MDIO_CLK_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MDIO_CLK_CONF_MDIO_CLK_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(5));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd1_cmd(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd1_Cmd_PinMux_V9:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_CSN(2)) =
					   (0 << CONTROL_CONF_GPMC_CSN2_CONF_GPMC_CSN2_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_CSN2_CONF_GPMC_CSN2_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_CSN2_CONF_GPMC_CSN2_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_CSN2_CONF_GPMC_CSN2_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(2));
		break;
	case Mmcsd1_Cmd_PinMux_K16:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXD1) =
					   (0 << CONTROL_CONF_MII1_TXD1_CONF_MII1_TXD1_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_TXD1_CONF_MII1_TXD1_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_TXD1_CONF_MII1_TXD1_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_TXD1_CONF_MII1_TXD1_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(6));
		break;
	case Mmcsd1_Cmd_PinMux_M17:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MDIO_DATA) =
					   (0 << CONTROL_CONF_MDIO_DATA_CONF_MDIO_DATA_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MDIO_DATA_CONF_MDIO_DATA_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MDIO_DATA_CONF_MDIO_DATA_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MDIO_DATA_CONF_MDIO_DATA_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(5));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd1_dat0(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd1_Dat0_PinMux_U10:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(8)) =
					   (0 << CONTROL_CONF_GPMC_AD8_CONF_GPMC_AD8_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD8_CONF_GPMC_AD8_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD8_CONF_GPMC_AD8_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD8_CONF_GPMC_AD8_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(2));
		break;
	case Mmcsd1_Dat0_PinMux_K18:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXD1) =
					   (0 << CONTROL_CONF_MII1_TXD1_CONF_MII1_TXD1_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_TXD1_CONF_MII1_TXD1_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_TXD1_CONF_MII1_TXD1_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_TXD1_CONF_MII1_TXD1_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(6));
		break;
	case Mmcsd1_Dat0_PinMux_U7:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(0)) =
					   (0 << CONTROL_CONF_GPMC_AD0_CONF_GPMC_AD0_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD0_CONF_GPMC_AD0_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD0_CONF_GPMC_AD0_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD0_CONF_GPMC_AD0_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(1));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd1_dat1(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd1_Dat1_PinMux_T10:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(9)) =
					   (0 << CONTROL_CONF_GPMC_AD9_CONF_GPMC_AD9_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD9_CONF_GPMC_AD9_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD9_CONF_GPMC_AD9_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD9_CONF_GPMC_AD9_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(2));
		break;
	case Mmcsd1_Dat1_PinMux_L18:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXCLK) =
					   (0 << CONTROL_CONF_MII1_RXCLK_CONF_MII1_RXCLK_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_RXCLK_CONF_MII1_RXCLK_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_RXCLK_CONF_MII1_RXCLK_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_RXCLK_CONF_MII1_RXCLK_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(4));
		break;
	case Mmcsd1_Dat1_PinMux_V7:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(1)) =
					   (0 << CONTROL_CONF_GPMC_AD1_CONF_GPMC_AD1_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD1_CONF_GPMC_AD1_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD1_CONF_GPMC_AD1_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD1_CONF_GPMC_AD1_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(1));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd1_dat2(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd1_Dat2_PinMux_T11:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(10)) =
					   (0 << CONTROL_CONF_GPMC_AD10_CONF_GPMC_AD10_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD10_CONF_GPMC_AD10_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD10_CONF_GPMC_AD10_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD10_CONF_GPMC_AD10_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(2));
		break;
	case Mmcsd1_Dat2_PinMux_L17:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXD3) =
					   (0 << CONTROL_CONF_MII1_RXD3_CONF_MII1_RXD3_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_RXD3_CONF_MII1_RXD3_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_RXD3_CONF_MII1_RXD3_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_RXD3_CONF_MII1_RXD3_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(4));
		break;
	case Mmcsd1_Dat2_PinMux_R8:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(2)) =
					   (0 << CONTROL_CONF_GPMC_AD2_CONF_GPMC_AD2_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD2_CONF_GPMC_AD2_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD2_CONF_GPMC_AD2_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD2_CONF_GPMC_AD2_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(1));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd1_dat3(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd1_Dat3_PinMux_U12:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(11)) =
					   (0 << CONTROL_CONF_GPMC_AD11_CONF_GPMC_AD11_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD11_CONF_GPMC_AD11_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD11_CONF_GPMC_AD11_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD11_CONF_GPMC_AD11_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(2));
		break;
	case Mmcsd1_Dat3_PinMux_L16:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXD2) =
					   (0 << CONTROL_CONF_MII1_RXD2_CONF_MII1_RXD2_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_RXD2_CONF_MII1_RXD2_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_RXD2_CONF_MII1_RXD2_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_RXD2_CONF_MII1_RXD2_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(4));
		break;
	case Mmcsd1_Dat3_PinMux_T8:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(3)) =
					   (0 << CONTROL_CONF_GPMC_AD3_CONF_GPMC_AD3_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD3_CONF_GPMC_AD3_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD3_CONF_GPMC_AD3_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD3_CONF_GPMC_AD3_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(1));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd1_dat4(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd1_Dat4_PinMux_T12:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(12)) =
					   (0 << CONTROL_CONF_GPMC_AD12_CONF_GPMC_AD12_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD12_CONF_GPMC_AD12_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD12_CONF_GPMC_AD12_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD12_CONF_GPMC_AD12_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(2));
		break;
	case Mmcsd1_Dat4_PinMux_U8:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(4)) =
					   (0 << CONTROL_CONF_GPMC_AD4_CONF_GPMC_AD4_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD4_CONF_GPMC_AD4_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD4_CONF_GPMC_AD4_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD4_CONF_GPMC_AD4_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(1));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd1_dat5(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd1_Dat5_PinMux_R12:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(13)) =
					   (0 << CONTROL_CONF_GPMC_AD13_CONF_GPMC_AD13_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD13_CONF_GPMC_AD13_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD13_CONF_GPMC_AD13_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD13_CONF_GPMC_AD13_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(2));
		break;
	case Mmcsd1_Dat5_PinMux_V8:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(5)) =
					   (0 << CONTROL_CONF_GPMC_AD5_CONF_GPMC_AD5_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD5_CONF_GPMC_AD5_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD5_CONF_GPMC_AD5_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD5_CONF_GPMC_AD5_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(1));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd1_dat6(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd1_Dat6_PinMux_V13:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(14)) =
					   (0 << CONTROL_CONF_GPMC_AD14_CONF_GPMC_AD14_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD14_CONF_GPMC_AD14_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD14_CONF_GPMC_AD14_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD14_CONF_GPMC_AD14_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(2));
		break;
	case Mmcsd1_Dat6_PinMux_R9:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(6)) =
					   (0 << CONTROL_CONF_GPMC_AD6_CONF_GPMC_AD6_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD6_CONF_GPMC_AD6_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD6_CONF_GPMC_AD6_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD6_CONF_GPMC_AD6_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(1));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd1_dat7(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd1_Dat7_PinMux_U13:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(15)) =
					   (0 << CONTROL_CONF_GPMC_AD15_CONF_GPMC_AD15_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD15_CONF_GPMC_AD15_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD15_CONF_GPMC_AD15_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD15_CONF_GPMC_AD15_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(2));
		break;
	case Mmcsd1_Dat7_PinMux_T9:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(7)) =
					   (0 << CONTROL_CONF_GPMC_AD7_CONF_GPMC_AD7_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD7_CONF_GPMC_AD7_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD7_CONF_GPMC_AD7_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD7_CONF_GPMC_AD7_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(1));
		break;
	default:
		return 0;
	}
	return 1;
}
/**********************************************/
unsigned int pin_mux_mmcsd2_clk(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd2_Clk_PinMux_L15:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXD1) =
					   (0 << CONTROL_CONF_MII1_RXD1_CONF_MII1_RXD1_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_RXD1_CONF_MII1_RXD1_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_RXD1_CONF_MII1_RXD1_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_RXD1_CONF_MII1_RXD1_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(6));
		break;
	case Mmcsd2_Clk_PinMux_M18:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MDIO_CLK) =
					   (0 << CONTROL_CONF_MDIO_CLK_CONF_MDIO_CLK_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MDIO_CLK_CONF_MDIO_CLK_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MDIO_CLK_CONF_MDIO_CLK_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MDIO_CLK_CONF_MDIO_CLK_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(6));
		break;
	case Mmcsd2_Clk_PinMux_V12:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_CLK) =
					   (0 << CONTROL_CONF_GPMC_CLK_CONF_GPMC_CLK_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_CLK_CONF_GPMC_CLK_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_CLK_CONF_GPMC_CLK_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_CLK_CONF_GPMC_CLK_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd2_cmd(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd2_Cmd_PinMux_J16:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXEN) =
					   (0 << CONTROL_CONF_MII1_TXEN_CONF_MII1_TXEN_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_TXEN_CONF_MII1_TXEN_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_TXEN_CONF_MII1_TXEN_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_TXEN_CONF_MII1_TXEN_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(6));
		break;
	case Mmcsd2_Cmd_PinMux_M17:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MDIO_DATA) =
					   (0 << CONTROL_CONF_MDIO_DATA_CONF_MDIO_DATA_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MDIO_DATA_CONF_MDIO_DATA_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MDIO_DATA_CONF_MDIO_DATA_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MDIO_DATA_CONF_MDIO_DATA_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(6));
		break;
	case Mmcsd2_Cmd_PinMux_T13:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_CSN(3)) =
					   (0 << CONTROL_CONF_GPMC_CSN3_CONF_GPMC_CSN3_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_CSN3_CONF_GPMC_CSN3_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_CSN3_CONF_GPMC_CSN3_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_CSN3_CONF_GPMC_CSN3_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(1));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd2_dat0(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd2_Dat0_PinMux_T12:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(12)) =
					   (0 << CONTROL_CONF_GPMC_AD12_CONF_GPMC_AD12_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD12_CONF_GPMC_AD12_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD12_CONF_GPMC_AD12_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD12_CONF_GPMC_AD12_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat0_PinMux_V14:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_A(1)) =
					   (0 << CONTROL_CONF_GPMC_A1_CONF_GPMC_A1_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_A1_CONF_GPMC_A1_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_A1_CONF_GPMC_A1_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_A1_CONF_GPMC_A1_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat0_PinMux_J17:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_RXDV) =
					   (0 << CONTROL_CONF_MII1_RXDV_CONF_MII1_RXDV_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_RXDV_CONF_MII1_RXDV_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_RXDV_CONF_MII1_RXDV_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_RXDV_CONF_MII1_RXDV_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(5));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd2_dat1(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd2_Dat1_PinMux_R12:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(13)) =
					   (0 << CONTROL_CONF_GPMC_AD13_CONF_GPMC_AD13_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD13_CONF_GPMC_AD13_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD13_CONF_GPMC_AD13_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD13_CONF_GPMC_AD13_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat1_PinMux_U14:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_A(2)) =
					   (0 << CONTROL_CONF_GPMC_A2_CONF_GPMC_A2_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_A2_CONF_GPMC_A2_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_A2_CONF_GPMC_A2_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_A2_CONF_GPMC_A2_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat1_PinMux_J18:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXD3) =
					   (0 << CONTROL_CONF_MII1_TXD3_CONF_MII1_TXD3_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_TXD3_CONF_MII1_TXD3_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_TXD3_CONF_MII1_TXD3_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_TXD3_CONF_MII1_TXD3_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(5));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd2_dat2(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd2_Dat2_PinMux_V13:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(14)) =
					   (0 << CONTROL_CONF_GPMC_AD14_CONF_GPMC_AD14_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD14_CONF_GPMC_AD14_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD14_CONF_GPMC_AD14_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD14_CONF_GPMC_AD14_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat2_PinMux_T14:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_A(3)) =
					   (0 << CONTROL_CONF_GPMC_A3_CONF_GPMC_A3_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_A3_CONF_GPMC_A3_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_A3_CONF_GPMC_A3_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_A3_CONF_GPMC_A3_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat2_PinMux_K15:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_TXD2) =
					   (0 << CONTROL_CONF_MII1_TXD2_CONF_MII1_TXD2_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_TXD2_CONF_MII1_TXD2_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_TXD2_CONF_MII1_TXD2_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_TXD2_CONF_MII1_TXD2_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(5));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd2_dat3(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd2_Dat3_PinMux_U18:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_BE1N) =
					   (0 << CONTROL_CONF_GPMC_BE1N_CONF_GPMC_BE1N_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_BE1N_CONF_GPMC_BE1N_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_BE1N_CONF_GPMC_BE1N_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_BE1N_CONF_GPMC_BE1N_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat3_PinMux_U13:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(15)) =
					   (0 << CONTROL_CONF_GPMC_AD15_CONF_GPMC_AD15_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD15_CONF_GPMC_AD15_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD15_CONF_GPMC_AD15_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD15_CONF_GPMC_AD15_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat3_PinMux_H16:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_MII1_COL) =
					   (0 << CONTROL_CONF_MII1_COL_CONF_MII1_COL_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_MII1_COL_CONF_MII1_COL_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_MII1_COL_CONF_MII1_COL_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_MII1_COL_CONF_MII1_COL_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(5));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd2_dat4(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd2_Dat4_PinMux_U10:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(8)) =
					   (0 << CONTROL_CONF_GPMC_AD8_CONF_GPMC_AD8_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD8_CONF_GPMC_AD8_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD8_CONF_GPMC_AD8_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD8_CONF_GPMC_AD8_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat4_PinMux_U15:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_A(6)) =
					   (0 << CONTROL_CONF_GPMC_A6_CONF_GPMC_A6_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_A6_CONF_GPMC_A6_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_A6_CONF_GPMC_A6_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_A6_CONF_GPMC_A6_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd2_dat5(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd2_Dat5_PinMux_T10:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(9)) =
					   (0 << CONTROL_CONF_GPMC_AD9_CONF_GPMC_AD9_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD9_CONF_GPMC_AD9_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD9_CONF_GPMC_AD9_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD9_CONF_GPMC_AD9_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat5_PinMux_T15:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_A(7)) =
					   (0 << CONTROL_CONF_GPMC_A7_CONF_GPMC_A7_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_A7_CONF_GPMC_A7_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_A7_CONF_GPMC_A7_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_A7_CONF_GPMC_A7_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd2_dat6(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd2_Dat6_PinMux_T11:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(10)) =
					   (0 << CONTROL_CONF_GPMC_AD10_CONF_GPMC_AD10_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD10_CONF_GPMC_AD10_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD10_CONF_GPMC_AD10_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD10_CONF_GPMC_AD10_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat6_PinMux_V16:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_A(8)) =
					   (0 << CONTROL_CONF_GPMC_A8_CONF_GPMC_A8_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_A8_CONF_GPMC_A8_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_A8_CONF_GPMC_A8_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_A8_CONF_GPMC_A8_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	default:
		return 0;
	}
	return 1;
}

unsigned int pin_mux_mmcsd2_dat7(unsigned int PinNr)
{
	switch(PinNr)
	{
	case Mmcsd2_Dat7_PinMux_U12:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_AD(11)) =
					   (0 << CONTROL_CONF_GPMC_AD11_CONF_GPMC_AD11_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_AD11_CONF_GPMC_AD11_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_AD11_CONF_GPMC_AD11_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_AD11_CONF_GPMC_AD11_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	case Mmcsd2_Dat7_PinMux_U16:
		HWREG(SOC_CONTROL_REGS + CONTROL_CONF_GPMC_A(9)) =
					   (0 << CONTROL_CONF_GPMC_A9_CONF_GPMC_A9_MMODE_SHIFT)    |
					   (0 << CONTROL_CONF_GPMC_A9_CONF_GPMC_A9_PUDEN_SHIFT)    |
					   (1 << CONTROL_CONF_GPMC_A9_CONF_GPMC_A9_PUTYPESEL_SHIFT)|
					   (1 << CONTROL_CONF_GPMC_A9_CONF_GPMC_A9_RXACTIVE_SHIFT  |
				                CONTROL_CONF_MUXMODE(3));
		break;
	default:
		return 0;
	}
	return 1;
}



