/*
 * clk_mcspi.c
 *
 *  Created on: Feb 2, 2013
 *      Author: XxXx
 */

#include <stdbool.h>
#include "clk_mcspi.h"
#include "include/l4per_cm2.h"

bool McSPIModuleClkConfig(unsigned char instance)
{
	switch(instance)
	{
	case 0:
    	L4PER_CM2.CM_L4PER_MCSPI1_CLKCTRL = CM_L4PER_MODULEMODE_EXPLICIT_ENABLE << CM_L4PER_MODULEMODE_gp;
    	while((L4PER_CM2.CM_L4PER_MCSPI1_CLKCTRL & CM_L4PER_MODULEMODE_gm) != (CM_L4PER_MODULEMODE_EXPLICIT_ENABLE << CM_L4PER_MODULEMODE_gp));
		while((L4PER_CM2.CM_L4PER_MCSPI1_CLKCTRL & CM_L4PER_IDLEST_gm) != (CM_L4PER_IDLEST_FULL_FUNCTIONAL << CM_L4PER_IDLEST_gp));
    	return true;
	case 1:
    	L4PER_CM2.CM_L4PER_MCSPI2_CLKCTRL = CM_L4PER_MODULEMODE_EXPLICIT_ENABLE << CM_L4PER_MODULEMODE_gp;
    	while((L4PER_CM2.CM_L4PER_MCSPI2_CLKCTRL & CM_L4PER_MODULEMODE_gm) != (CM_L4PER_MODULEMODE_EXPLICIT_ENABLE << CM_L4PER_MODULEMODE_gp));
		while((L4PER_CM2.CM_L4PER_MCSPI2_CLKCTRL & CM_L4PER_IDLEST_gm) != (CM_L4PER_IDLEST_FULL_FUNCTIONAL << CM_L4PER_IDLEST_gp));
    	return true;
	case 2:
    	L4PER_CM2.CM_L4PER_MCSPI3_CLKCTRL = CM_L4PER_MODULEMODE_EXPLICIT_ENABLE << CM_L4PER_MODULEMODE_gp;
    	while((L4PER_CM2.CM_L4PER_MCSPI3_CLKCTRL & CM_L4PER_MODULEMODE_gm) != (CM_L4PER_MODULEMODE_EXPLICIT_ENABLE << CM_L4PER_MODULEMODE_gp));
		while((L4PER_CM2.CM_L4PER_MCSPI3_CLKCTRL & CM_L4PER_IDLEST_gm) != (CM_L4PER_IDLEST_FULL_FUNCTIONAL << CM_L4PER_IDLEST_gp));
    	return true;
	case 3:
    	L4PER_CM2.CM_L4PER_MCSPI4_CLKCTRL = CM_L4PER_MODULEMODE_EXPLICIT_ENABLE << CM_L4PER_MODULEMODE_gp;
    	while((L4PER_CM2.CM_L4PER_MCSPI4_CLKCTRL & CM_L4PER_MODULEMODE_gm) != (CM_L4PER_MODULEMODE_EXPLICIT_ENABLE << CM_L4PER_MODULEMODE_gp));
		while((L4PER_CM2.CM_L4PER_MCSPI4_CLKCTRL & CM_L4PER_IDLEST_gm) != (CM_L4PER_IDLEST_FULL_FUNCTIONAL << CM_L4PER_IDLEST_gp));
    	return true;
	}
	return false;
}

bool McSPIModuleClkUnConfig(unsigned char instance)
{
    switch (instance)
    {
    case 0:
    	L4PER_CM2.CM_L4PER_MCSPI1_CLKCTRL &= ~CM_L4PER_MODULEMODE_gm;
    	while(L4PER_CM2.CM_L4PER_MCSPI1_CLKCTRL & CM_L4PER_MODULEMODE_gm);
    	return true;
    case 1:
    	L4PER_CM2.CM_L4PER_MCSPI2_CLKCTRL &= ~CM_L4PER_MODULEMODE_gm;
    	while(L4PER_CM2.CM_L4PER_MCSPI2_CLKCTRL & CM_L4PER_MODULEMODE_gm);
    	return true;
    case 2:
    	L4PER_CM2.CM_L4PER_MCSPI3_CLKCTRL &= ~CM_L4PER_MODULEMODE_gm;
    	while(L4PER_CM2.CM_L4PER_MCSPI3_CLKCTRL & CM_L4PER_MODULEMODE_gm);
    	return true;
    case 3:
    	L4PER_CM2.CM_L4PER_MCSPI4_CLKCTRL &= ~CM_L4PER_MODULEMODE_gm;
    	while(L4PER_CM2.CM_L4PER_MCSPI4_CLKCTRL & CM_L4PER_MODULEMODE_gm);
    	return true;
    }
    return false;
}

