/*
 * clk_gpio.c
 *
 *  Created on: Jan 13, 2013
 *      Author: XxXx
 */

#include <stdbool.h>
#include "clk_gpio.h"
#include "include/l4per_cm2.h"
#include "include/wkup_cm.h"

bool GPIOModuleClkConfig(unsigned int GpioModuleNr)
{
	switch(GpioModuleNr)
	{
	case 0:
		WKUP_CM.CM_WKUP_GPIO1_CLKCTRL = WKUP_CM_MODULEMODE_EXPLICIT_ENABLE << WKUP_CM_MODULEMODE_gp;
		while((WKUP_CM.CM_WKUP_GPIO1_CLKCTRL & WKUP_CM_MODULEMODE_gm) != (WKUP_CM_MODULEMODE_EXPLICIT_ENABLE << WKUP_CM_MODULEMODE_gp));
		while((WKUP_CM.CM_WKUP_GPIO1_CLKCTRL & WKUP_CM_IDLEST_gm) != (WKUP_CM_IDLEST_FULL_FUNCTIONAL << WKUP_CM_IDLEST_gp))
		return true;
	case 1:
		L4PER_CM2.CM_L4PER_GPIO2_CLKCTRL = CM_L4PER_MODULEMODE_AUTOMATIC << CM_L4PER_MODULEMODE_gp;
		while((L4PER_CM2.CM_L4PER_GPIO2_CLKCTRL & CM_L4PER_MODULEMODE_gm) != (CM_L4PER_MODULEMODE_AUTOMATIC << CM_L4PER_MODULEMODE_gp));
		while((L4PER_CM2.CM_L4PER_GPIO2_CLKCTRL & CM_L4PER_IDLEST_gm) != (CM_L4PER_IDLEST_FULL_FUNCTIONAL << CM_L4PER_IDLEST_gp))
		return true;
	case 2:
		L4PER_CM2.CM_L4PER_GPIO3_CLKCTRL = CM_L4PER_MODULEMODE_AUTOMATIC << CM_L4PER_MODULEMODE_gp;
		while((L4PER_CM2.CM_L4PER_GPIO3_CLKCTRL & CM_L4PER_MODULEMODE_gm) != (CM_L4PER_MODULEMODE_AUTOMATIC << CM_L4PER_MODULEMODE_gp));
		while((L4PER_CM2.CM_L4PER_GPIO3_CLKCTRL & CM_L4PER_IDLEST_gm) != (CM_L4PER_IDLEST_FULL_FUNCTIONAL << CM_L4PER_IDLEST_gp))
		return true;
	case 3:
		L4PER_CM2.CM_L4PER_GPIO4_CLKCTRL = CM_L4PER_MODULEMODE_AUTOMATIC << CM_L4PER_MODULEMODE_gp;
		while((L4PER_CM2.CM_L4PER_GPIO4_CLKCTRL & CM_L4PER_MODULEMODE_gm) != (CM_L4PER_MODULEMODE_AUTOMATIC << CM_L4PER_MODULEMODE_gp));
		while((L4PER_CM2.CM_L4PER_GPIO4_CLKCTRL & CM_L4PER_IDLEST_gm) != (CM_L4PER_IDLEST_FULL_FUNCTIONAL << CM_L4PER_IDLEST_gp))
		return true;
	case 4:
		L4PER_CM2.CM_L4PER_GPIO5_CLKCTRL = CM_L4PER_MODULEMODE_AUTOMATIC << CM_L4PER_MODULEMODE_gp;
		while((L4PER_CM2.CM_L4PER_GPIO5_CLKCTRL & CM_L4PER_MODULEMODE_gm) != (CM_L4PER_MODULEMODE_AUTOMATIC << CM_L4PER_MODULEMODE_gp));
		while((L4PER_CM2.CM_L4PER_GPIO5_CLKCTRL & CM_L4PER_IDLEST_gm) != (CM_L4PER_IDLEST_FULL_FUNCTIONAL << CM_L4PER_IDLEST_gp))
		return true;
	case 5:
		L4PER_CM2.CM_L4PER_GPIO6_CLKCTRL = CM_L4PER_MODULEMODE_AUTOMATIC << CM_L4PER_MODULEMODE_gp;
		while((L4PER_CM2.CM_L4PER_GPIO6_CLKCTRL & CM_L4PER_MODULEMODE_gm) != (CM_L4PER_MODULEMODE_AUTOMATIC << CM_L4PER_MODULEMODE_gp));
		while((L4PER_CM2.CM_L4PER_GPIO6_CLKCTRL & CM_L4PER_IDLEST_gm) != (CM_L4PER_IDLEST_FULL_FUNCTIONAL << CM_L4PER_IDLEST_gp))
		return true;
	}
	return false;
}

bool GPIOModuleClkUnConfig(unsigned int GpioModuleNr)
{
	switch(GpioModuleNr)
	{
	case 0:
		WKUP_CM.CM_WKUP_GPIO1_CLKCTRL &= ~WKUP_CM_MODULEMODE_gm;
		while((WKUP_CM.CM_WKUP_GPIO1_CLKCTRL & WKUP_CM_MODULEMODE_gm));
		return true;
	case 1:
		L4PER_CM2.CM_L4PER_GPIO2_CLKCTRL &= ~CM_L4PER_MODULEMODE_gm;
		while((L4PER_CM2.CM_L4PER_GPIO2_CLKCTRL & WKUP_CM_MODULEMODE_gm));
		return true;
	case 2:
		L4PER_CM2.CM_L4PER_GPIO3_CLKCTRL &= ~CM_L4PER_MODULEMODE_gm;
		while((L4PER_CM2.CM_L4PER_GPIO3_CLKCTRL & WKUP_CM_MODULEMODE_gm));
		return true;
	case 3:
		L4PER_CM2.CM_L4PER_GPIO4_CLKCTRL &= ~CM_L4PER_MODULEMODE_gm;
		while((L4PER_CM2.CM_L4PER_GPIO4_CLKCTRL & WKUP_CM_MODULEMODE_gm));
		return true;
	case 4:
		L4PER_CM2.CM_L4PER_GPIO5_CLKCTRL &= ~CM_L4PER_MODULEMODE_gm;
		while((L4PER_CM2.CM_L4PER_GPIO5_CLKCTRL & WKUP_CM_MODULEMODE_gm));
		return true;
	case 5:
		L4PER_CM2.CM_L4PER_GPIO6_CLKCTRL &= ~CM_L4PER_MODULEMODE_gm;
		while((L4PER_CM2.CM_L4PER_GPIO6_CLKCTRL & WKUP_CM_MODULEMODE_gm));
		return true;
	}
	return false;
}

