#ifndef MIKROMEDIA_FOR_STM32E4
#define MIKROMEDIA_FOR_STM32E4

#include "api/gpio_def.h"

//#define LED1_PORT			IOC
//#define LED1_PIN			13
//#define LED1_INVERSE		true

#define LEDS_NR				0

//#define HARDBTN1_PORT		IOA
//#define HARDBTN1_PIN		0

#define HARDBTNS_NR			0

#define DEFAULT_UART_UNIT		1
#define DEFAULT_UART_TX_PORT	IOD
#define DEFAULT_UART_TX_PIN		5
#define DEFAULT_UART_RX_PORT	IOD
#define DEFAULT_UART_RX_PIN		6

#define DEFAULT_I2C_UNIT		0
#define DEFAULT_I2C_SCL_PORT	IOB
#define DEFAULT_I2C_SCL_PIN	6
#define DEFAULT_I2C_SDA_PORT	IOB
#define DEFAULT_I2C_SDA_PIN	7

#define DEFAULT_SPI_UNIT		2
#define DEFAULT_SPI_SCK_PORT	IOC
#define DEFAULT_SPI_SCK_PIN		10
#define DEFAULT_SPI_MOSI_PORT	IOC
#define DEFAULT_SPI_MOSI_PIN	11
#define DEFAULT_SPI_MISO_PORT	IOC
#define DEFAULT_SPI_MISO_PIN	12
#define DEFAULT_SPI_CD_PORT		IOD//SD_CD
#define DEFAULT_SPI_CD_PIN		15
#define DEFAULT_SPI_CS0_PORT	IOD//SD_CS
#define DEFAULT_SPI_CS0_PIN		3
#define DEFAULT_SPI_CS1_PORT	IOD//M25P80
#define DEFAULT_SPI_CS1_PIN		7
#define DEFAULT_SPI_CS2_PORT	IOC//VS1053_CS
#define DEFAULT_SPI_CS2_PIN		8
#define DEFAULT_SPI_CS3_PORT	IOC///VS1053_DCS
#define DEFAULT_SPI_CS3_PIN		9

#define NRF24L01_SPI_UNIT		1
#define NRF24L01_SPI_SCK_PORT	IOB
#define NRF24L01_SPI_SCK_PIN	13
#define NRF24L01_SPI_MOSI_PORT	IOB
#define NRF24L01_SPI_MOSI_PIN	15
#define NRF24L01_SPI_MISO_PORT	IOB
#define NRF24L01_SPI_MISO_PIN	14
#define NRF24L01_SPI_CS0_PORT	IOB//NRF24L01_CS
#define NRF24L01_SPI_CS0_PIN	12
#define NRF24L01_IRQ_PORT		IOB
#define NRF24L01_IRQ_PIN		11
#define NRF24L01_CE_PORT		IOB
#define NRF24L01_CE_PIN			10

#define LCD_DATA_PORT			IOE
#define LCD_CONTROL_PORT		IOE
#define LCD_DATA_PIN_MASK		0xFF
#define LCD_BACKLIGHT_PORT		IOE
#define LCD_BACKLIGHT_PIN		9
#define LCD_TOUCH_DRIVE_A_PORT	IOB
#define LCD_TOUCH_DRIVE_A_PIN	8
#define LCD_TOUCH_DRIVE_B_PORT	IOB
#define LCD_TOUCH_DRIVE_B_PIN	9
#define LCD_TOUCH_XL_PORT		IOB
#define LCD_TOUCH_XL_PIN		1
#define LCD_TOUCH_YD_PORT		IOB
#define LCD_TOUCH_YD_PIN		0
#define LCD_DISPLAY_RST_PORT	IOE
#define LCD_DISPLAY_RST_PIN		8
#define LCD_DISPLAY_RS_PORT		IOE
#define LCD_DISPLAY_RS_PIN		12
#define LCD_DISPLAY_CS_PORT		IOE
#define LCD_DISPLAY_CS_PIN		15
#define LCD_DISPLAY_PMWR_PORT	IOE
#define LCD_DISPLAY_PMWR_PIN	11
#define LCD_DISPLAY_PMRD_PORT	IOE
#define LCD_DISPLAY_PMRD_PIN	10


#define BAT_STAT_PORT			IOC
#define BAT_STAT_PIN			13

#endif
