#ifndef __STM32F469I_DISCO__
#define __STM32F469I_DISCO__


#define LED1_PORT			IOG
#define LED1_PIN			6
#define LED1_INVERSE		true

#define LED2_PORT			IOD
#define LED2_PIN			4
#define LED2_INVERSE		true

#define LED3_PORT			IOD
#define LED3_PIN			5
#define LED3_INVERSE		true

#define LED4_PORT			IOK
#define LED4_PIN			3
#define LED4_INVERSE		true

#define LEDS_NR				4

#define HARDBTN1_PORT		IOA
#define HARDBTN1_PIN		0

#define HARDBTNS_NR			1

#define DEFAULT_UART_UNIT		2
#define DEFAULT_UART_TX_PORT	IOB
#define DEFAULT_UART_TX_PIN		10
#define DEFAULT_UART_RX_PORT	IOB
#define DEFAULT_UART_RX_PIN		11

#define DEFAULT_I2C_UNIT		0
#define DEFAULT_I2C_SCL_PORT	IOB
#define DEFAULT_I2C_SCL_PIN	8
#define DEFAULT_I2C_SDA_PORT	IOB
#define DEFAULT_I2C_SDA_PIN	9

#define AUDIO_I2C_UNIT		1
#define AUDIO_I2C_SCL_PORT	IOH
#define AUDIO_I2C_SCL_PIN	4
#define AUDIO_I2C_SDA_PORT	IOH
#define AUDIO_I2C_SDA_PIN	5

#define SPI_EXTENSION_UNIT		0
#define SPI_EXTENSION_SCK_PORT	IOA
#define SPI_EXTENSION_SCK_PIN	5
#define SPI_EXTENSION_MOSI_PORT	IOB
#define SPI_EXTENSION_MOSI_PIN	5
#define SPI_EXTENSION_MISO_PORT	IOB
#define SPI_EXTENSION_MISO_PIN	4
#define SPI_EXTENSION_CS1_PORT	IOA//SD_CD
#define SPI_EXTENSION_CS1_PIN	15

#define LCD_BACKLIGHT_PORT		IOA
#define LCD_BACKLIGHT_PIN		3
#define LCD_DISPLAY_RST_PORT	IOH
#define LCD_DISPLAY_RST_PIN		7
#define LCD_TOUCH_INT_PORT		IOJ
#define LCD_TOUCH_INT_PIN		5

#define SD_CD_PORT				IOG
#define SD_CD_PIN				2

#define BAT_STAT_PORT			IOC
#define BAT_STAT_PIN			13

#endif
